FROM node:12

WORKDIR /usr/src/app/server

COPY package.json ./

COPY yarn.lock ./

RUN yarn

COPY . .

COPY .env.production .env

RUN yarn build

ENV NODE_ENV production

EXPOSE 8080

CMD [ "yarn", "production" ]

USER node